import type { ModuleDef } from "@/lib/module-sdk";

/**
 * Lazy loaders for every built module, keyed "<track>/<module>".
 * Each import becomes its own bundle, so heavy modules (3D, sandboxes)
 * never slow down other pages. Paths must be literal for the bundler.
 */
export const moduleLoaders: Record<string, () => Promise<{ default: ModuleDef }>> = {
  "playground/rows-vs-columns": () => import("./playground/rows-vs-columns"),
  "data-lakehouse/swamp-to-lakehouse": () => import("./data-lakehouse/swamp-to-lakehouse"),
  "data-lakehouse/object-storage": () => import("./data-lakehouse/object-storage"),
  "data-lakehouse/file-formats": () => import("./data-lakehouse/file-formats"),
  "data-lakehouse/inside-parquet": () => import("./data-lakehouse/inside-parquet"),
  "data-lakehouse/what-makes-a-table": () => import("./data-lakehouse/what-makes-a-table"),
  "data-lakehouse/delta-lake": () => import("./data-lakehouse/delta-lake"),
  "data-lakehouse/apache-iceberg": () => import("./data-lakehouse/apache-iceberg"),
  "data-lakehouse/apache-hudi": () => import("./data-lakehouse/apache-hudi"),
  "data-lakehouse/format-showdown": () => import("./data-lakehouse/format-showdown"),
  "data-lakehouse/acid-and-concurrency": () => import("./data-lakehouse/acid-and-concurrency"),
  "data-lakehouse/updates-and-deletes": () => import("./data-lakehouse/updates-and-deletes"),
  "data-lakehouse/schema-evolution": () => import("./data-lakehouse/schema-evolution"),
  "data-lakehouse/partitioning": () => import("./data-lakehouse/partitioning"),
  "data-lakehouse/data-skipping": () => import("./data-lakehouse/data-skipping"),
  "data-lakehouse/table-maintenance": () => import("./data-lakehouse/table-maintenance"),
  "data-lakehouse/catalogs": () => import("./data-lakehouse/catalogs"),
  "data-lakehouse/governance-security": () => import("./data-lakehouse/governance-security"),
  "data-lakehouse/ingestion": () => import("./data-lakehouse/ingestion"),
  "data-lakehouse/cdc-and-merge": () => import("./data-lakehouse/cdc-and-merge"),
  "data-lakehouse/medallion": () => import("./data-lakehouse/medallion"),
  "data-lakehouse/query-engines": () => import("./data-lakehouse/query-engines"),
  "data-lakehouse/hands-on-sql": () => import("./data-lakehouse/hands-on-sql"),
  "data-lakehouse/bi-ml-ai": () => import("./data-lakehouse/bi-ml-ai"),
  "data-lakehouse/on-aws": () => import("./data-lakehouse/on-aws"),
  "data-lakehouse/on-gcp": () => import("./data-lakehouse/on-gcp"),
  "data-lakehouse/on-azure": () => import("./data-lakehouse/on-azure"),
  "data-lakehouse/landscape": () => import("./data-lakehouse/landscape"),
  "data-lakehouse/design-a-lakehouse": () => import("./data-lakehouse/design-a-lakehouse"),
  "data-lakehouse/fix-the-lakehouse": () => import("./data-lakehouse/fix-the-lakehouse"),
  "system-design/what-scale-means": () => import("./system-design/what-scale-means"),
  "system-design/latency-throughput": () => import("./system-design/latency-throughput"),
  "system-design/estimation": () => import("./system-design/estimation"),
  "system-design/load-balancing": () => import("./system-design/load-balancing"),
  "system-design/autoscaling": () => import("./system-design/autoscaling"),
  "system-design/cdn-edge": () => import("./system-design/cdn-edge"),
  "system-design/caching-patterns": () => import("./system-design/caching-patterns"),
  "system-design/cache-eviction": () => import("./system-design/cache-eviction"),
  "system-design/replication": () => import("./system-design/replication"),
  "system-design/sharding": () => import("./system-design/sharding"),
  "system-design/consistency": () => import("./system-design/consistency"),
  "system-design/choosing-a-database": () => import("./system-design/choosing-a-database"),
  "system-design/distributed-transactions": () =>
    import("./system-design/distributed-transactions"),
  "system-design/queues-streams": () => import("./system-design/queues-streams"),
  "system-design/retries-idempotency": () => import("./system-design/retries-idempotency"),
  "system-design/event-driven": () => import("./system-design/event-driven"),
  "system-design/availability": () => import("./system-design/availability"),
  "system-design/resilience-patterns": () => import("./system-design/resilience-patterns"),
  "system-design/multi-region-dr": () => import("./system-design/multi-region-dr"),
  "system-design/observability": () => import("./system-design/observability"),
  "system-design/url-shortener": () => import("./system-design/url-shortener"),
};
