/** C4 levels for a claims system, and a technology radar to fill in (illustrative). */

export const C4 = [
  {
    level: "System context",
    who: "Anyone, including non-technical people",
    boxes: [
      { l: "Policyholder", kind: "person" },
      { l: "Claims system", kind: "focus" },
      { l: "Payment gateway", kind: "external" },
      { l: "Policy mainframe", kind: "external" },
    ],
    text: "Your system as one box in the middle, with the people who use it and the systems it talks to.",
  },
  {
    level: "Container",
    who: "Developers and operations",
    boxes: [
      { l: "Web app", kind: "focus" },
      { l: "Claims API", kind: "focus" },
      { l: "Claims database", kind: "focus" },
      { l: "Event broker", kind: "external" },
    ],
    text: "Inside the system: each application or data store that must be running. Not Docker containers, though one may run in one.",
  },
  {
    level: "Component",
    who: "Developers on this container",
    boxes: [
      { l: "ApproveClaim", kind: "focus" },
      { l: "PolicyStore port", kind: "focus" },
      { l: "Postgres adapter", kind: "focus" },
      { l: "SMS adapter", kind: "focus" },
    ],
    text: "Inside one container: groups of related functionality behind clear interfaces. Not separately deployable.",
  },
  {
    level: "Code",
    who: "Usually generated by tools, if at all",
    boxes: [
      { l: "class ApproveClaim", kind: "focus" },
      { l: "interface PolicyStore", kind: "focus" },
      { l: "class Claim", kind: "focus" },
    ],
    text: "Classes and interfaces. Rarely worth drawing by hand.",
  },
];

export type Ring = "adopt" | "trial" | "assess" | "caution";

export const RINGS: Record<Ring, { name: string; r: number; d: string }> = {
  adopt: { name: "Adopt", r: 30, d: "Proven; use it." },
  trial: { name: "Trial", r: 55, d: "Worth pursuing on a project that can handle the risk." },
  assess: { name: "Assess", r: 80, d: "Worth exploring to understand." },
  caution: { name: "Caution", r: 105, d: "Proceed with care; significant concerns." },
};

export const BLIPS: { id: string; l: string; a: number }[] = [
  { id: "pg", l: "PostgreSQL", a: 20 },
  { id: "kafka", l: "Kafka", a: 60 },
  { id: "temporal", l: "Temporal", a: 110 },
  { id: "agent", l: "AI coding agents", a: 150 },
  { id: "esb", l: "ESB for new work", a: 200 },
  { id: "mesh", l: "Service mesh", a: 250 },
];
